#!/usr/bin/env ruby
require 'rubygems'
Gem.clear_paths
Gem.path.unshift(File.join(File.dirname(__FILE__), "gems"))
require 'merb-core'

init_env = ENV['MERB_ENV'] || 'development'
Merb.start_environment(:environment => init_env, :adapter => 'runner')


Panda::Setup.create_s3_bucket if Panda::Config[:use_s3]
Panda::Setup.create_sdb_domains # This can run many times, it doesn't re-create them.

# These can run many times, they just copy files into public/
Store.set('player.swf', 'public/player.swf')
Store.set('swfobject2.js', 'public/javascripts/swfobject2.js')
Store.set('expressInstall.swf', 'public/expressInstall.swf')

# Set up an Admin user if not already set up.
u = User.find('admin') rescue nil
unless u
  puts <<-ADMIN_INSTRUCTIONS.gsub(/^\s+\|/,'')
    |**********
    |You don't have an admin user created. You may want to set this up manually in IRB:
    |
    |  u = User.new
    |  u.login = 'admin'
    |  u.email = 'admin_email@example.com'
    |  u.set_password('password')
    |  u.save
    |
    |**********
  ADMIN_INSTRUCTIONS
end

# Create an encoding profile. More can be found at the first url at the top of this document.
# This new/save method (specifying the record-key) allows us to run this as many times as we want and it only creates one record.
p = Profile.new('Flash video SD', :title => "Flash video SD",  :container => "flv", :video_bitrate => 300, :audio_bitrate => 48, :width => 320, :height => 240, :fps => 24, :position => 0, :player => "flash")
p.save
