#!/usr/bin/env ruby
require 'rubygems'

puts "Installing any gems missing..."
['spec:rspec', 'merb-core', 'rubigen', 'merb-assets', 'merb-mailer', 'merb_helpers', 'uuid', 'mongrel', 'amazon_sdb', 'rvideo:mhs-rvideo:0.9.4', 'inline:RubyInline', 'aws/s3:aws-s3', 'flv:flvtool2'].each do |dep|
  lib, gemname, version = dep.split(':')
  gemname ||= lib
  begin
    require lib
  rescue LoadError
    puts "Installing #{gemname}..."
    system("sudo env PATH=$PATH gem install --no-ri --no-rdoc #{gemname}#{' --version '+version if version}")
  end
end
puts "Done with gems."
